#!/usr/bin/env ruby
# frozen_string_literal: true

$LOAD_PATH.unshift(File.expand_path('lib', __dir__))
require 'price_calculator'

puts 'Please enter all the items purchased separated by a comma'
groceries = gets.chomp.split(',').map(&:strip).map(&:downcase)

# Scan our groceries at the Register
register = PriceCalculator::Register.new
response = register.scan(*groceries)

if response.valid?
  receipt = response.data
  puts "\nItem\tQuantity\tPrice"
  puts '--------------------------------------'
  receipt.items.each do |item|
    puts "#{item.name}\t #{item.quantity}\t\t$#{item.discounted_price.to_f}"
  end

  puts "\nTotal price : $#{receipt.total_due.to_f}"
  puts "You saved $#{receipt.discount_applied.to_f} today." if receipt.discount_applied.positive?
else
  response.errors.each do |error_message|
    puts error_message
  end
end
